/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biodatanew;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class NewBiodata extends javax.swing.JFrame {

    String name, gender, nim, prodi, alamat, hobbyWorkout, hobbyMartialArts, hobbyRunning, hobbySinging, hobbyGames;
    /**
     * Creates new form ProfileInputUI
     */
    public NewBiodata() {
        initComponents();
        
        Color bg = new Color(255,255,255);
        getContentPane().setBackground(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNama1 = new javax.swing.JTextField();
        TxtNIM1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTNClear = new javax.swing.JButton();
        BTNProcess = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AlamatArea = new javax.swing.JTextArea();
        ComboProdi = new javax.swing.JComboBox<>();
        RadioButtonM = new javax.swing.JRadioButton();
        RadioButtonF = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        checkhobbyWorkout = new javax.swing.JCheckBox();
        checkhobbyMartialArts = new javax.swing.JCheckBox();
        checkhobbyRunning = new javax.swing.JCheckBox();
        checkhobbySinging = new javax.swing.JCheckBox();
        checkhobbyGames = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel2.setText("NIM:");

        jLabel3.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel3.setText("Major:");

        jLabel4.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel4.setText("Address:");

        TxtNama1.setBackground(new java.awt.Color(233, 233, 233));
        TxtNama1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNama1ActionPerformed(evt);
            }
        });

        TxtNIM1.setBackground(new java.awt.Color(233, 233, 233));
        TxtNIM1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtNIM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIM1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");

        BTNClear.setBackground(new java.awt.Color(255, 204, 204));
        BTNClear.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        BTNClear.setForeground(new java.awt.Color(153, 0, 0));
        BTNClear.setText("Clear");
        BTNClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClearActionPerformed(evt);
            }
        });

        BTNProcess.setBackground(new java.awt.Color(204, 255, 204));
        BTNProcess.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        BTNProcess.setForeground(new java.awt.Color(0, 102, 0));
        BTNProcess.setText("Process");
        BTNProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNProcessActionPerformed(evt);
            }
        });

        AlamatArea.setBackground(new java.awt.Color(233, 233, 233));
        AlamatArea.setColumns(20);
        AlamatArea.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        AlamatArea.setRows(5);
        jScrollPane2.setViewportView(AlamatArea);

        ComboProdi.setFont(new java.awt.Font("Satoshi Variable", 0, 12)); // NOI18N
        ComboProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Desain Komunikasi & Visual", "Manajemen", "International Business Management" }));

        GroupGender.add(RadioButtonM);
        RadioButtonM.setText("Male");
        RadioButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMActionPerformed(evt);
            }
        });

        GroupGender.add(RadioButtonF);
        RadioButtonF.setText("Female");

        jLabel6.setFont(new java.awt.Font("Satoshi Variable", 1, 14)); // NOI18N
        jLabel6.setText("Hobby:");

        checkhobbyWorkout.setText("Workout");

        checkhobbyMartialArts.setText("Martial Arts");

        checkhobbyRunning.setText("Running");

        checkhobbySinging.setText("Singing");

        checkhobbyGames.setText("Games");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\D\\Downloads\\undraw_Swipe_profiles_re_tvqm (1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkhobbyMartialArts)
                            .addComponent(checkhobbyWorkout)
                            .addComponent(checkhobbyRunning)
                            .addComponent(checkhobbySinging)
                            .addComponent(checkhobbyGames)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RadioButtonM)
                                        .addGap(26, 26, 26)
                                        .addComponent(RadioButtonF))
                                    .addComponent(TxtNIM1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RadioButtonM)
                            .addComponent(RadioButtonF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNIM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ComboProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkhobbyWorkout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkhobbyMartialArts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkhobbyRunning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkhobbySinging)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkhobbyGames)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNIM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNIM1ActionPerformed

    private void TxtNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNama1ActionPerformed

    private void BTNProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNProcessActionPerformed
        // TODO add your handling code here:
        name = TxtNama1.getText();
        nim = TxtNIM1.getText();
        prodi = ComboProdi.getSelectedItem().toString();
        alamat = AlamatArea.getText();
        
        //condition for choosing the gender
        if(RadioButtonM.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }
        
        //condition for choosing hobbies
        if(checkhobbyWorkout.isSelected()) {
            hobbyWorkout = "Workout";
        } else {
            hobbyWorkout = "";
        }
        
        if(checkhobbyMartialArts.isSelected()) {
            hobbyMartialArts = "Martial Arts";
        } else {
            hobbyMartialArts = "";
        }

        if(checkhobbyRunning.isSelected()) {
            hobbyRunning = "Running";
        } else {
            hobbyRunning = "";
        }
        
        if(checkhobbySinging.isSelected()) {
            hobbySinging = "Singing";
        } else {
            hobbySinging = "";
        }
        
        if(checkhobbyGames.isSelected()) {
            hobbyGames = "Games";
        } else {
            hobbyGames = "";
        }
        
        JOptionPane.showMessageDialog(this, "Name : " + name+ "\nGender : "+ gender + "\nNIM : " + nim + "\nMajor : " + prodi + "\nAddress : " + alamat + "\nHobbies : " + "\n" + hobbyWorkout + "\n" + hobbyMartialArts + "\n" + hobbyRunning + "\n" + hobbyGames, "Biodata", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BTNProcessActionPerformed

    private void BTNClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClearActionPerformed
        // TODO add your handling code here:
        TxtNama1.setText("");
        TxtNIM1.setText("");
        GroupGender.clearSelection();
        ComboProdi.setSelectedItem("None");
        AlamatArea.setText("");
        checkhobbyWorkout.setSelected(false);
        checkhobbyMartialArts.setSelected(false);
        checkhobbyRunning.setSelected(false);
        checkhobbySinging.setSelected(false);
        checkhobbyGames.setSelected(false);
    }//GEN-LAST:event_BTNClearActionPerformed

    private void RadioButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlamatArea;
    private javax.swing.JButton BTNClear;
    private javax.swing.JButton BTNProcess;
    private javax.swing.JComboBox<String> ComboProdi;
    private javax.swing.ButtonGroup GroupGender;
    private javax.swing.JRadioButton RadioButtonF;
    private javax.swing.JRadioButton RadioButtonM;
    private javax.swing.JTextField TxtNIM1;
    private javax.swing.JTextField TxtNama1;
    private javax.swing.JCheckBox checkhobbyGames;
    private javax.swing.JCheckBox checkhobbyMartialArts;
    private javax.swing.JCheckBox checkhobbyRunning;
    private javax.swing.JCheckBox checkhobbySinging;
    private javax.swing.JCheckBox checkhobbyWorkout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
